[project]
name = "asrc_turbopi_services"
# import-names = ["turbocore"]
version = "0.0.1"
authors = [
  { name="Kevin Zhu", email="kzhu4@gmu.edu" },
]
dependencies = [
  "RPi.GPIO",
  "python-statemachine",
  "psutil",
  "rpi_ws281x",
  "textual",
  "rich",
]
description = "Code to interface with HiWonder Rasadapter for TurboPi"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
four = ["rasadapter4"]

# [project.urls]
# Homepage = "https://github.com/pypa/sampleproject"
# Issues = "https://github.com/pypa/sampleproject/issues"